### ISSUE TITLE
SHM reduceAdd performance issue on HBM with 2 sockets

### ISSUE THREAD

**Issue by abenmao** [intel/xFasterTransformer#154] opened 2023-12-26 07:11 UTC
Llama-2-7b BF16 145in 198out
batch size=1:

| reduce-type          | first token                                   | second token
| ----------------- | ----------------------------------|----------------------- |
| 1s       |  117       |   41      |
| 2s-SHM        |   350      |   42      |
| 2s-ONECCL        |     135      |     25       |

batch size=38

| reduce-type          | first token                                   | second token
| ----------------- | ----------------------------------|----------------------- |
| 1s       |     3500    |    88.9     |
| 2s-SHM        |   1926      |  426      |
| 2s-ONECCL        |     4912     |     63       |

**Comment by shanzhou2186** [comment] 2023-12-27 03:33
bs=1 bf16 128 in out 198:    1socket 1st: 204ms, 34ms
                                              2s default SHM 1st: 128ms, 21ms

**Comment by shanzhou2186** [comment] 2023-12-27 03:58
Just checked another machine with the same hbm CPU in flat+quad mode, the result can't be reproduced. The issue should be caused by a special machine, which needs more analysis. But it's not a common software issue. We will close it and reopen it if it happens again. @abenmao

**Closed by shanzhou2186** 2023-12-27 03:58 UTC
